[package]
name = "xkcd-ascii"
version = "0.1.0"
authors = ["HKG <hkg902@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "1.0.3"
image = "0.22.3"
clap = "2.33.0"
